os: osx
osx_image: xcode7.2
language: c
sudo: false

env:
 - THEOS=theos

before_script:
 - brew update
 - brew install dpkg ldid
 - git clone --recursive https://github.com/theos/theos.git

script:
 - make
