language: generic

env:
 - THEOS=theos

before_script:
 - git clone --recursive https://github.com/theos/theos.git

script:
 - make

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
      before_script:
        - brew update
        - brew install dpkg ldid
