matrix:
  include:
    - os: osx
      osx_image: xcode7.2
      sudo: false
    - os: linux
      dist: trusty
      sudo: required

env:
 - THEOS=theos

before_script:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update            ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install dpkg ldid ; fi
 - git clone --recursive https://github.com/theos/theos.git

script:
 - make
